# Use an Nginx image to serve static files
FROM nginx:alpine

# Copy frontend files to Nginx default directory
COPY ./app/frontend /usr/share/nginx/html

# Expose Nginx default port
EXPOSE 80

# Run Nginx
CMD ["nginx", "-g", "daemon off;"]
