# Use official Python image
FROM python:3.10-slim

# Set working directory in the container
WORKDIR /app

# Copy backend files
COPY ./app/backend /app

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose FastAPI default port
EXPOSE 8000

# Command to run the FastAPI app
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
